### ISSUE TITLE
Is it possible to set my custom layout for section header?

### ISSUE THREAD

**Issue by michaldarda** [nolanlawson/SuperSaiyanScrollView#6]
Hey,

I want to set custom layout for my sectioned list and displayed number of elements in it, is it possible with this library?

**Comment by nolanlawson** [comment]
Currently, no.  However, it should be pretty easy to override in the source code.  [This](https://github.com/nolanlawson/SuperSaiyanScrollView/blob/master/supersaiyan-scrollview/src/com/nolanlawson/supersaiyan/SectionTitleAdapter.java#L28) is the adapter I'm using to display the section titles, and I instantiate it somewhere by just passing in a very basic layout file (`layoutResId`).  Presumably I could allow users to set this layout file resource ID somewhere in the code.

BTW pull requests are always welcome!  :smiley:
