### ISSUE TITLE
Section colors

### ISSUE THREAD

**Issue by ghost** [nolanlawson/SuperSaiyanScrollView#9]
Hi Sir, sorry for bother you, but, I would like to know if is it possible to change the color of the sections?

I would like to change the background color from white to blue, just of  the section and keep the white color of my list view.

This is an example where the section color is green.

![image](https://cloud.githubusercontent.com/assets/6497625/5443286/9fbe040c-8472-11e4-989b-acc88e427723.png)

Thanks for everything

**Comment by ghost** [comment]
I think that I got my own answer at looking at this: https://github.com/nolanlawson/SuperSaiyanScrollView/issues/6

Thanks sir.

**Comment by nolanlawson** [comment]
Glad you got your answer. :)
